"""`splunkctl docs generate` — the generated command reference.

Walks the same runnable-command tree as `commands` and writes one markdown
page per top-level group into docs/commands/ plus an index, and syncs the
marker-delimited block in docs/_sidebar.md — so the docs-site reference can
never drift from the CLI. Hidden: a maintainer/CI tool, not an operator
surface. `--check` regenerates in memory and fails when the committed files
are stale (the CI freshness gate).
"""

from dataclasses import dataclass
from pathlib import Path

import click

from splunkctl.guard import is_guarded

_START = "<!-- commands:start -->"
_END = "<!-- commands:end -->"
_NOTICE = "<!-- Generated by `splunkctl docs generate` — do not edit by hand. -->"


@click.group("docs", hidden=True)
def docs_group() -> None:
    """Generate documentation and command-reference pages (maintainers)."""


@dataclass
class _Entry:
    """One runnable command with its full path (e.g. ``soar playbooks list``)."""

    path: str
    cmd: click.Command


@dataclass
class _Group:
    """One reference page: a top-level command group and its runnable commands.

    Single leaf top-level commands (doctor, info, ...) are folded into the
    synthetic "global" group.
    """

    name: str
    short: str
    entries: list[_Entry]


def _first_line(text: str | None) -> str:
    return (text or "").split("\n")[0].strip()


def _walk(group: click.Group, prefix: str, out: list[_Entry]) -> None:
    """Collect every visible runnable command under ``group``."""
    for name, cmd in sorted(group.commands.items()):
        if cmd.hidden:
            continue
        path = f"{prefix} {name}".strip()
        if isinstance(cmd, click.Group):
            _walk(cmd, path, out)
        else:
            out.append(_Entry(path, cmd))


def _collect_groups(root: click.Group) -> list[_Group]:
    """Bucket every runnable command by its top-level segment.

    A top-level command with no subcommands lands in "global"; groups are
    sorted by name with "global" last.
    """
    entries: list[_Entry] = []
    _walk(root, "", entries)

    shorts = {name: _first_line(cmd.help) for name, cmd in root.commands.items()}

    by_top: dict[str, list[_Entry]] = {}
    for e in entries:
        top = e.path.split(" ")[0]
        by_top.setdefault(top, []).append(e)

    groups: list[_Group] = []
    global_entries: list[_Entry] = []
    for top, es in sorted(by_top.items()):
        # A single entry whose path IS the top-level name is a plain leaf
        # command (doctor, info, commands, ...) — folded into "global".
        if len(es) == 1 and es[0].path == top:
            global_entries.append(es[0])
            continue
        groups.append(_Group(top, shorts.get(top, ""), es))
    if global_entries:
        groups.append(_Group("global", "Top-level commands", global_entries))
    return groups


def _cell(s: str) -> str:
    """Make a string safe inside a one-line markdown table cell."""
    return " ".join(s.replace("|", "\\|").split())


def _usage(e: _Entry) -> str:
    ctx = click.Context(e.cmd, info_name=f"splunkctl {e.path}")
    pieces = e.cmd.collect_usage_pieces(ctx)
    return " ".join([f"splunkctl {e.path}", *pieces])


def _long_help(e: _Entry) -> str:
    r"""Body of the command help below the summary line, ``\b`` markers dropped."""
    lines = (e.cmd.help or "").split("\n")[1:]
    return "\n".join(ln for ln in lines if ln.strip() != "\b").strip()


def _flag_default(p: click.Option) -> str:
    d = p.default
    if isinstance(d, bool):
        return "true" if d else "false"
    # Only scalar defaults are meaningful in docs — sentinels, tuples, and
    # callables render as "-".
    if isinstance(d, (str, int, float)) and d != "":
        return str(d)
    return "-"


def _flag_type(p: click.Option) -> str:
    if isinstance(p.type, click.Choice):
        return "choice: " + ", ".join(str(c) for c in p.type.choices)
    if p.is_flag:
        return "flag"
    return p.type.name


def _flag_rows(cmd: click.Command) -> list[str]:
    """Render the command's options as markdown table rows."""
    rows: list[str] = []
    for p in cmd.params:
        if not isinstance(p, click.Option) or p.hidden or p.name == "help":
            continue
        shorts = [o for o in p.opts if not o.startswith("--")]
        longs = [o for o in p.opts if o.startswith("--")]
        name = ", ".join(shorts + longs)
        if p.secondary_opts:
            name += " / " + ", ".join(p.secondary_opts)
        desc = p.help or ""
        if p.required:
            desc = f"{desc} [required]".strip()
        rows.append(
            f"| `{_cell(name)}` | {_cell(_flag_type(p))}"
            f" | {_cell(_flag_default(p))} | {_cell(desc)} |"
        )
    return rows


def _render_entry(e: _Entry) -> list[str]:
    out = [f"## {e.path}", ""]
    if short := _first_line(e.cmd.help):
        out += [short, ""]
    if is_guarded(e.cmd):
        out += ["> Guarded mutation — dry-run by default; apply with `--yes`.", ""]
    out += ["```text", _usage(e), "```"]

    # The long help is CLI help text, not authored markdown — fence it
    # verbatim so stray tables/lists/pipes inside it can never break the page.
    if long := _long_help(e):
        fence = "~~~~" if "```" in long else "```"
        out += ["", f"{fence}text", long, fence]

    if rows := _flag_rows(e.cmd):
        out += [
            "",
            "**Flags**",
            "",
            "| Flag | Type | Default | Description |",
            "|---|---|---|---|",
            *rows,
        ]
    return out


def _render_group(g: _Group) -> str:
    title = "Global commands" if g.name == "global" else f"splunkctl {g.name}"
    lines = [_NOTICE, "", f"# {title}", ""]
    if g.short:
        lines.append(g.short)
    for e in g.entries:
        lines += ["", *_render_entry(e)]
    return "\n".join(lines) + "\n"


def _render_index(groups: list[_Group]) -> str:
    lines = [
        _NOTICE,
        "",
        "# Command reference",
        "",
        "Generated from the Click command tree — run `splunkctl docs generate`",
        'after changing a command. "Guarded" commands are live mutations behind',
        "the standard dry-run/`--yes` gate; everything else is a read.",
        "",
        "| Group | Commands | Description |",
        "|---|---|---|",
    ]
    for g in groups:
        lines.append(
            f"| [{g.name}]({g.name}.md) | {len(g.entries)} | {_cell(g.short)} |"
        )
    return "\n".join(lines) + "\n"


def _render_pages(groups: list[_Group]) -> dict[str, str]:
    """Render every group page plus the index, keyed by filename."""
    pages = {f"{g.name}.md": _render_group(g) for g in groups}
    pages["README.md"] = _render_index(groups)
    return pages


def _sidebar_block(pages: dict[str, str]) -> str:
    names = sorted(n.removesuffix(".md") for n in pages if n != "README.md")
    lines = [_START, "- **Command reference**", "  - [Overview](commands/README.md)"]
    lines += [f"  - [{n}](commands/{n}.md)" for n in names]
    lines.append(_END)
    return "\n".join(lines)


def _patch_sidebar(content: str, block: str) -> str:
    """Replace the marker-delimited sidebar block, or insert before Design."""
    if (start := content.find(_START)) >= 0:
        end = content.find(_END)
        if end < start:
            raise click.ClickException(
                f"sidebar: {_START} found without a following {_END}"
            )
        return content[:start] + block + content[end + len(_END) :]
    anchor = "- **Design**"
    if (i := content.find(anchor)) >= 0:
        return content[:i] + block + "\n\n" + content[i:]
    return content.rstrip("\n") + "\n\n" + block + "\n"


def _stale_pages(pages: dict[str, str], out_dir: Path) -> list[str]:
    """Committed *.md files the current command tree no longer generates."""
    if not out_dir.is_dir():
        return []
    return sorted(
        f.name
        for f in out_dir.iterdir()
        if f.is_file() and f.name.endswith(".md") and f.name not in pages
    )


def _write_docs(pages: dict[str, str], out_dir: Path, sidebar: str) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, content in pages.items():
        (out_dir / name).write_text(content, encoding="utf-8")
    stale = _stale_pages(pages, out_dir)
    for name in stale:
        (out_dir / name).unlink()
    if sidebar:
        path = Path(sidebar)
        raw = path.read_text(encoding="utf-8")
        path.write_text(_patch_sidebar(raw, _sidebar_block(pages)), encoding="utf-8")
    msg = f"generated {len(pages)} page(s) in {out_dir}"
    if stale:
        msg += f", removed {len(stale)} stale"
    click.echo(msg)


def _check_docs(pages: dict[str, str], out_dir: Path, sidebar: str) -> list[str]:
    problems: list[str] = []
    for name, content in pages.items():
        f = out_dir / name
        if not f.is_file():
            problems.append(f"missing: {name}")
        elif f.read_text(encoding="utf-8") != content:
            problems.append(f"stale: {name}")
    problems += [f"orphaned: {name}" for name in _stale_pages(pages, out_dir)]
    if sidebar:
        raw = Path(sidebar).read_text(encoding="utf-8")
        if _patch_sidebar(raw, _sidebar_block(pages)) != raw:
            problems.append(f"stale: {sidebar} command-reference block")
    return sorted(problems)


@docs_group.command("generate")
@click.option(
    "--out",
    "out_dir",
    default="docs/commands",
    help="Output directory for the generated pages.",
)
@click.option(
    "--sidebar",
    default="docs/_sidebar.md",
    help="Sidebar file to sync (empty to skip).",
)
@click.option(
    "--check",
    is_flag=True,
    help="Verify the committed pages are current; write nothing.",
)
@click.pass_context
def docs_generate(ctx: click.Context, out_dir: str, sidebar: str, check: bool) -> None:
    """Generate the per-group command-reference pages under docs/commands/.

    Walk the command tree and write one markdown page per top-level command
    group into docs/commands/ (plus an index README), and sync the
    commands:start/end block in docs/_sidebar.md. With --check, nothing is
    written: the run fails when any committed page, the index, or the
    sidebar block is stale — the CI freshness gate.
    """
    root = ctx.find_root().command
    if not isinstance(root, click.Group):
        raise click.ClickException("Cannot resolve CLI root.")
    pages = _render_pages(_collect_groups(root))
    if check:
        if problems := _check_docs(pages, Path(out_dir), sidebar):
            click.echo(
                "command reference is out of date — run `splunkctl docs generate`:",
                err=True,
            )
            for p in problems:
                click.echo(f"  {p}", err=True)
            ctx.exit(1)
        click.echo("ok: command reference is current")
        return
    _write_docs(pages, Path(out_dir), sidebar)
